### ISSUE TITLE
Prepare initial release

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#133]
A lot of work has already gone into this plugin, so it's about time we get to the most important stuff - release it! 🚢 

This issue should serve as a bit of an overview for the things we need to cover before our initial release. See the tasks below:

* [x] Define scope of the initial release, i.e. which modules should be included in which state (discussion starting in https://github.com/WordPress/performance/issues/133#issuecomment-1024056958)
* [x] Decide on the version number to use for this initial release (see https://github.com/WordPress/performance/issues/133#issuecomment-1024051757)
* [x] Add release documentation (see #131)
* [x] Finalize GitHub configuration for automatic deployment (see #42)
* [x] Prepare release based on steps in the above documentation (should be a PR for this issue)

**Comment by felixarntz** [comment]
_Please vote for this approach with a thumbs-up or thumbs-down emoji. Voting will close on 8 Feb 2022 at 6pm GMT._

The "easy" things first: Let's decide on the version number to use. Currently the milestone is named `1.0.0-beta.1` - which we can definitely change - however **I'd like to suggest actually using `1.0.0-beta.1` for our first release** since:
* `1.0.0` is an appropriate first version.
* The `-beta.1` suffix should be there since we haven't done any beta testing before.

**Comment by felixarntz** [comment]
In addition to the above vote, let's discuss a bit on the scope:
* So far we only have the WebP for new image uploads module.
* We're also about to have the first Site Health module, informing about excessive JS and CSS assets being loaded (see #54).
* Both of these modules are definitely not in their final shape (e.g. the [WebP implementation is pending a decision here](https://github.com/WordPress/performance/issues/96#issuecomment-1016458629), and the Site Health assets module needs follow-up enhancements already determined during PR review).
* However, both of the modules are properly usable - they are not "broken" in any way and _could_ be tested even in their current form.

My personal suggestion therefore is to limit our first release to these two modules, IMO that's good for a start. What I'm unsure about is at which stage we should ship them, should we wait for some of these more crucial enhancements being implemented first, or is it worth giving the current version out to people already (especially given that it would be a beta release anyway)?

Curious to hear y'all's thoughts!

cc @adamsilverstein @getsource @audrasjb @manuelRod @aristath

**Comment by JustinyAhin** [comment]
@felixarntz let's also add "Create release assets" as part of the preparation. We will need a banner, a logo, and also screenshots.

**Comment by felixarntz** [comment]
@JustinyAhin I agree that would be great to have, though I'm not sure it is a strict requirement. None of that is truly _needed_ for a plugin. Again, I'm not saying we shouldn't have it, but I don't think it's a blocker to release. With that said, if we want to have a banner and a logo, I think we should reach out with the wider team as soon as possible and ask if there are any volunteer designers who would like to come up with something - maybe something for the chat tomorrow @bethanylang?

Regarding screenshots, we can definitely get that done.

**Comment by JustinyAhin** [comment]
> Again, I'm not saying we shouldn't have it, but I don't think it's a blocker to release.

@felixarntz I agree on that, let's not make it a blocker for the release. 

> Regarding screenshots, we can definitely get that done.

Yes, that will be a good start.

**Comment by mxbclang** [comment]
Clarifying here that the decision needed is for the vote on this comment: https://github.com/WordPress/performance/issues/133#issuecomment-1024051757.

In addition, the Needs Discussion label for the scope: https://github.com/WordPress/performance/issues/133#issuecomment-1024056958.

**Comment by adamsilverstein** [comment]
> My personal suggestion therefore is to limit our first release to these two modules,

This sounds fine as long as the release is clearly labeled beta, especially since the webp approach is changing significantly.

**Comment by mxbclang** [comment]
**Voting is now closed.**

Based on **8** thumbs up votes and **no** thumbs down votes, we'll proceed with this behavior:

Using 1.0.0-beta.1 for our first release.

Removing the Needs Decision label. Discussion remains open for the scope items noted in https://github.com/WordPress/performance/issues/133#issuecomment-1024056958.

**Comment by JustinyAhin** [comment]
> What I'm unsure about is at which stage we should ship them, should we wait for some of these more crucial enhancements being implemented first, or is it worth giving the current version out to people already (especially given that it would be a beta release anyway)?

About this, I think some enhancements have been addressed already. 
https://github.com/WordPress/performance/issues/22 seems like to have a long way to go.

I'd suggest we release a beta version with the two modules in their current state, and iterate on the current issues/enhancements.

Releasing now also have the advantage of having more people testing the plugin, and more feedback as well.


cc @bethanylang @eclarke1 @felixarntz.

**Comment by felixarntz** [comment]
The tricky part of shipping the current version of the WebP module would be that it will result in people's sites that use it no longer having JPEG sub-size versions of their JPEG uploads. This is probably not a big deal for many, but I'm wary of shipping it because it is in a way "destructive" behavior. I'd feel more comfortable if we had _some_ implementation of having JPEG _and_ WebP being generated.

**Comment by mxbclang** [comment]
_Please vote for this approach with a thumbs-up or thumbs-down emoji. Voting will close on **Tuesday 1 March 2022 at 6pm GMT**._

Thumbs up 👍 :  We will ship the initial release of the plugin **with** the WebP module in its current version, where it no longer generates JPEG images.

Thumbs down 👎 : We will ship the initial release of the plugin **without** the WebP module.

Heart ❤️ : We will delay the initial release until the WebP module has received support for generating both JPEG and WebP sizes.

We also welcome your thoughts on why you voted the way that you did in the comments on the issue. Thank you!

**Comment by felixarntz** [comment]
@bethanylang We may need to put a third option here like "We will delay the initial release until the WebP module has received support for generating both JPEG and WebP sizes." In that same sense, maybe the second option should be clarified that that would mean releasing a version that doesn't have the WebP module at all.

**Comment by mxbclang** [comment]
@felixarntz Updated!

**Comment by felixarntz** [comment]
Leaving an update here on the state of the WebP module: We still have the vote going on from https://github.com/WordPress/performance/issues/133#issuecomment-1040525560 which ends March 1, but there is a chance that the essential parts of the `webp-uploads` module that facilitate the creation of both JPEG and WebP sub-size images will even be completed before then. The two particular issues that need to be completed for that are #142 and #149.

One more issue that would be great to complete before beta release is #61, since it touches default behavior of the overall plugin.

**Comment by mxbclang** [comment]
Formally [closing the vote here](https://github.com/WordPress/performance/issues/133#issuecomment-1040525560) as the WebP module has received support for generating both JPEG and WebP sizes, so this is good to go for the initial release! 🎉

**Comment by felixarntz** [comment]
Providing an update here after today's chat:
* As discussed in the chat, we aim to publish the initial release 1.0.0-beta.1 on **Monday, March 7**. 🎉 
* In advance, I will prepare the repository for that initial deployment (configure the credentials) and draft a make.wordpress.org/core/ blog post announcement for the release.
* On **Monday, March 7 at 19:00 UTC** we will have the "release party chat" in the [performance Slack channel](https://wordpress.slack.com/archives/performance/), in which we'll work through the release publishing tasks together. Anyone available and willing to help with the release is welcome to join!

**Comment by felixarntz** [comment]
Important release update:
* I have branched off from `trunk` into a new [`release/1.0.0-beta.1` branch](https://github.com/WordPress/performance/tree/release/1.0.0-beta.1) and updated all relevant open PRs accordingly.
* If you are creating PRs that fix something that is critical before the beta release, please work off that branch instead of `trunk`.
* Any other PRs can be continued to be based off `trunk`. Those will then land in the following release when they are merged.

**Comment by felixarntz** [comment]
Quick update: The plugin repository is now properly configured with the `SVN_USERNAME` and `SVN_PASSWORD` secrets to auto-deploy to wordpress.org (using the `performanceteam` account created for that purpose). So we are now technically set up for the release.
