### ISSUE TITLE
Prepare 1.0.0-beta.2 release

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#213]
Now that the [initial release is out](https://make.wordpress.org/core/2022/03/07/the-performance-lab-plugin-has-been-released/) (🎉), it's time to plan for the next one: `1.0.0-beta.2`. See #133 for the similar task for the previous (initial) release.

This issue acts as an overview for the release preparation.

Here are the relevant tasks:

* [x] Revise release preparation approach based on issues encountered during initial release, based on [release party chat log](https://wordpress.slack.com/archives/C02KGN5K076/p1646679630345889) (see #214)
* [x] Define scope and tentative release date based on the scope
* [x] Create `release/1.0.0-beta.2` branch closer to the release date
* [x] Prepare the release (**Monday, March 21, 2022**, #245)

**Comment by felixarntz** [comment]
Given that we already got a couple of enhancements and fixes completed since the original launch last week, I think it's worth shipping the second beta `1.0.0-beta.2` sooner than later. We also have our branding #144 pretty much finalized at this point, so it would be a good time to include those in the wordpress.org deployment so that our plugin repository page looks less "boring" and more appealing than it does now, including our brand identity.

I suggest we plan for releasing **next Monday, March 21**. It looks quite realistic given the [milestone issues](https://github.com/WordPress/performance/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-beta.2) and [milestone pull requests](https://github.com/WordPress/performance/pulls?q=is%3Aopen+is%3Apr+milestone%3A1.0.0-beta.2), and it would be 2 weeks after the initial release - which overall I think it would be a good rhythm to release betas until we're comfortable enough to call it 1.0.0-rc.1.

Does that sound reasonable? We can discuss in our chat tomorrow as well.

**Comment by felixarntz** [comment]
Per the Slack performance chat earlier today, the plan is to go ahead with releasing on next **Monday, March 21**. Similar to the initial release, we will have a "release party" chat where everyone is welcome to join and participate in the release process live. This meeting will take place **Monday, March 21 at 17:00 UTC** in the #performance Slack channel as usual.

**Comment by felixarntz** [comment]
The [release branch `release/1.0.0-beta.2`](https://github.com/WordPress/performance/tree/release/1.0.0-beta.2) has now been created from `trunk`.

* Pull requests relevant for this upcoming beta should be based on `release/1.0.0-beta.2` going forward.
* Other pull requests for future releases can now continue to be merged into `trunk`.
