### ISSUE TITLE
Prepare 1.0.0-beta.3 release

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#249]
During the `1.0.0-beta.2` release (see #213), we identified a rather critical bug where the default setting value for active modules wouldn't trigger in time for when the plugin actually loads the active modules. This means that on plugin activation, all modules behave as if they're disabled, even though the UI in the settings screen shows they are enabled. See #247.

A temporary workaround for this is to save the settings on the settings screen, but this is a critical flaw that should be addressed promptly, hence a `1.0.0-beta.3` release should be created in a timely manner, with just this bug fix.

* [x] Define scope and tentative release date based on the scope
* [x] Create `release/1.0.0-beta.3` branch closer to the release date
* [x] Prepare the release (**Tuesday, March 22, 2022**)

**Comment by felixarntz** [comment]
With #248 merged, everything is set to publish `1.0.0-beta.3` today, to get this fix on people's sites promptly.
